/**
 * Parity test for `src/core/pluginRoot.ts` (F-087).
 *
 * Unlike canonicalHash / eventLog / state — which use static fixture
 * files generated by Python — pluginRoot's behaviour depends on
 * environment variables (`HOME`, `PATH`) and on a live filesystem
 * tree. We therefore mirror the Python `tests/unit/test_plugin_root.py`
 * scenarios in TypeScript: each test builds a temporary HOME +
 * marketplace + plugin directory layout, points the resolver at it,
 * and asserts the same strategy + path the Python helper would
 * choose.
 *
 * Coverage parity with the Python suite:
 *
 *   - StrategyA: hit, name-mismatch, PATH without `/plugins/`.
 *   - StrategyB: hit, miss-when-installpath-doesnt-exist, name-
 *     mismatch, registry-file-missing.
 *   - StrategyC: hit, non-directory marketplace skipped, no
 *     marketplaces.
 *   - Chain: full failure raises, A wins first, B wins when A misses,
 *     attempts trace tracked.
 *
 * Run via `npm run test:parity`.
 */

import {mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {afterEach, beforeEach, describe, expect, it} from 'vitest';

import {
  PluginRootError,
  _strategyMarketplaceSource,
  _strategyPathBin,
  _strategyRegistry,
  resolve as resolvePluginRoot,
} from '../../src/core/pluginRoot.js';

interface Scratch {
  tmp: string;
  home: string;
  pluginDir: string;
}

/**
 * Build a scratch tree mirroring the Python ScratchHomeMixin setUp.
 *
 * On macOS the system tmpdir is `/var/folders/...` which `realpath`
 * canonicalizes to `/private/var/folders/...`. The resolver returns
 * the canonical path; we store it here too so test assertions can
 * compare without surprise.
 */
function makeScratch(): Scratch {
  const tmpRaw = mkdtempSync(join(tmpdir(), 'pluginroot-'));
  const tmp = realpathSync(tmpRaw);
  const home = join(tmp, 'home');
  mkdirSync(join(home, '.claude', 'plugins'), {recursive: true});

  const pluginDir = join(tmp, 'harness-boot-repo');
  mkdirSync(join(pluginDir, '.claude-plugin'), {recursive: true});
  writeFileSync(
    join(pluginDir, '.claude-plugin', 'plugin.json'),
    JSON.stringify({name: 'harness', version: '0.1.1'}),
    'utf-8',
  );
  mkdirSync(join(pluginDir, 'bin'));

  return {tmp, home, pluginDir};
}

function writeRegistry(home: string, mapping: Record<string, unknown>): void {
  writeFileSync(
    join(home, '.claude', 'plugins', 'installed_plugins.json'),
    JSON.stringify(mapping),
    'utf-8',
  );
}

function writeSettings(home: string, data: Record<string, unknown>): void {
  writeFileSync(join(home, '.claude', 'settings.json'), JSON.stringify(data), 'utf-8');
}

function writeMarketplace(mpRoot: string, plugins: unknown[]): void {
  mkdirSync(join(mpRoot, '.claude-plugin'), {recursive: true});
  writeFileSync(
    join(mpRoot, '.claude-plugin', 'marketplace.json'),
    JSON.stringify({name: 'mp', owner: {name: 't'}, plugins}),
    'utf-8',
  );
}

/**
 * Sets up env overrides for one test; cleanup must happen in afterEach.
 *
 * Uses `process.env.HOME` rather than mocking `os.homedir` because
 * Node's homedir module is non-configurable under ESM and refuses to
 * be redefined. On POSIX, `os.homedir()` consults `$HOME` per call,
 * so swapping the env variable is observationally identical.
 */
function withEnv(home: string, pathValue: string): {restore: () => void} {
  const prevHome = process.env.HOME;
  const prevPath = process.env.PATH;
  process.env.HOME = home;
  process.env.PATH = pathValue;
  return {
    restore: () => {
      if (prevHome === undefined) {
        delete process.env.HOME;
      } else {
        process.env.HOME = prevHome;
      }
      if (prevPath === undefined) {
        delete process.env.PATH;
      } else {
        process.env.PATH = prevPath;
      }
    },
  };
}

describe('pluginRoot strategy A — $PATH /plugins/.../bin', () => {
  let scratch: Scratch;
  let envHandle: {restore: () => void} | null = null;

  beforeEach(() => {
    scratch = makeScratch();
  });
  afterEach(() => {
    envHandle?.restore();
    envHandle = null;
    rmSync(scratch.tmp, {recursive: true, force: true});
  });

  it('hits when PATH contains /plugins/<name>/bin and plugin.json.name matches', () => {
    const pluginInPlugins = join(scratch.tmp, 'plugins', 'harness-boot');
    mkdirSync(join(pluginInPlugins, '.claude-plugin'), {recursive: true});
    writeFileSync(
      join(pluginInPlugins, '.claude-plugin', 'plugin.json'),
      JSON.stringify({name: 'harness'}),
      'utf-8',
    );
    mkdirSync(join(pluginInPlugins, 'bin'));

    envHandle = withEnv(scratch.home, join(pluginInPlugins, 'bin'));
    expect(_strategyPathBin('harness')).toBe(pluginInPlugins);
  });

  it('skips entries whose plugin.json.name does not match', () => {
    const pluginInPlugins = join(scratch.tmp, 'plugins', 'other-plugin');
    mkdirSync(join(pluginInPlugins, '.claude-plugin'), {recursive: true});
    writeFileSync(
      join(pluginInPlugins, '.claude-plugin', 'plugin.json'),
      JSON.stringify({name: 'other'}),
      'utf-8',
    );
    mkdirSync(join(pluginInPlugins, 'bin'));

    envHandle = withEnv(scratch.home, join(pluginInPlugins, 'bin'));
    expect(_strategyPathBin('harness')).toBeNull();
  });

  it('skips PATH entries that do not contain /plugins/', () => {
    envHandle = withEnv(scratch.home, '/usr/bin:/bin:/usr/local/bin');
    expect(_strategyPathBin('harness')).toBeNull();
  });
});

describe('pluginRoot strategy B — installed_plugins.json', () => {
  let scratch: Scratch;
  let envHandle: {restore: () => void} | null = null;

  beforeEach(() => {
    scratch = makeScratch();
  });
  afterEach(() => {
    envHandle?.restore();
    envHandle = null;
    rmSync(scratch.tmp, {recursive: true, force: true});
  });

  it('hits when installPath exists on disk', () => {
    writeRegistry(scratch.home, {
      version: 2,
      plugins: {
        'harness@some-mp': [{installPath: scratch.pluginDir, version: '0.1.1'}],
      },
    });
    envHandle = withEnv(scratch.home, '/usr/bin');
    expect(_strategyRegistry('harness')).toBe(scratch.pluginDir);
  });

  it('misses when installPath is a phantom (NEW-44)', () => {
    writeRegistry(scratch.home, {
      version: 2,
      plugins: {
        'harness@some-mp': [{installPath: '/nonexistent/path', version: '0.1.1'}],
      },
    });
    envHandle = withEnv(scratch.home, '/usr/bin');
    expect(_strategyRegistry('harness')).toBeNull();
  });

  it('skips entries whose key does not start with the plugin name', () => {
    writeRegistry(scratch.home, {
      version: 2,
      plugins: {
        'other@some-mp': [{installPath: scratch.pluginDir}],
      },
    });
    envHandle = withEnv(scratch.home, '/usr/bin');
    expect(_strategyRegistry('harness')).toBeNull();
  });

  it('returns null when the registry file does not exist', () => {
    envHandle = withEnv(scratch.home, '/usr/bin');
    expect(_strategyRegistry('harness')).toBeNull();
  });
});

describe('pluginRoot strategy C — directory-type marketplace fallback', () => {
  let scratch: Scratch;
  let envHandle: {restore: () => void} | null = null;

  beforeEach(() => {
    scratch = makeScratch();
  });
  afterEach(() => {
    envHandle?.restore();
    envHandle = null;
    rmSync(scratch.tmp, {recursive: true, force: true});
  });

  it('combines marketplace path with plugin source', () => {
    const mpRoot = join(scratch.tmp, 'local-harness-marketplace');
    mkdirSync(mpRoot);

    const harnessSrc = join(mpRoot, 'harness-src');
    mkdirSync(join(harnessSrc, '.claude-plugin'), {recursive: true});
    writeFileSync(
      join(harnessSrc, '.claude-plugin', 'plugin.json'),
      JSON.stringify({name: 'harness'}),
      'utf-8',
    );

    writeMarketplace(mpRoot, [{name: 'harness', source: './harness-src'}]);
    writeSettings(scratch.home, {
      extraKnownMarketplaces: {
        'local-mp': {source: {source: 'directory', path: mpRoot}},
      },
    });

    envHandle = withEnv(scratch.home, '/usr/bin');
    expect(_strategyMarketplaceSource('harness')).toBe(harnessSrc);
  });

  it('skips non-directory marketplace types', () => {
    writeSettings(scratch.home, {
      extraKnownMarketplaces: {
        'remote-mp': {source: {source: 'github', repo: 'x/y'}},
      },
    });
    envHandle = withEnv(scratch.home, '/usr/bin');
    expect(_strategyMarketplaceSource('harness')).toBeNull();
  });

  it('returns null when no marketplaces are configured', () => {
    writeSettings(scratch.home, {});
    envHandle = withEnv(scratch.home, '/usr/bin');
    expect(_strategyMarketplaceSource('harness')).toBeNull();
  });
});

describe('pluginRoot.resolve — chain ordering', () => {
  let scratch: Scratch;
  let envHandle: {restore: () => void} | null = null;

  beforeEach(() => {
    scratch = makeScratch();
  });
  afterEach(() => {
    envHandle?.restore();
    envHandle = null;
    rmSync(scratch.tmp, {recursive: true, force: true});
  });

  it('throws PluginRootError with the attempt trace on full miss', () => {
    envHandle = withEnv(scratch.home, '/usr/bin');
    expect(() => resolvePluginRoot('harness')).toThrow(PluginRootError);
    try {
      resolvePluginRoot('harness');
    } catch (err) {
      expect((err as Error).message).toContain('A path-bin: miss');
      expect((err as Error).message).toContain('B registry: miss');
      expect((err as Error).message).toContain('C mp-source: miss');
      // Korean phrasing preserved verbatim from Python — log scrapers
      // can match either runtime with a single regex.
      expect((err as Error).message).toContain('루트 해석 실패');
    }
  });

  it('strategy A wins when both A and B are populated', () => {
    const pluginInPlugins = join(scratch.tmp, 'plugins', 'harness-boot');
    mkdirSync(join(pluginInPlugins, '.claude-plugin'), {recursive: true});
    writeFileSync(
      join(pluginInPlugins, '.claude-plugin', 'plugin.json'),
      JSON.stringify({name: 'harness'}),
      'utf-8',
    );
    mkdirSync(join(pluginInPlugins, 'bin'));

    writeRegistry(scratch.home, {
      version: 2,
      plugins: {'harness@mp': [{installPath: scratch.pluginDir}]},
    });

    envHandle = withEnv(scratch.home, join(pluginInPlugins, 'bin'));
    const result = resolvePluginRoot('harness');
    expect(result.strategy).toBe('A:path-bin');
    expect(result.root).toBe(pluginInPlugins);
  });

  it('strategy B wins when A misses', () => {
    writeRegistry(scratch.home, {
      version: 2,
      plugins: {'harness@mp': [{installPath: scratch.pluginDir}]},
    });
    envHandle = withEnv(scratch.home, '/usr/bin');
    const result = resolvePluginRoot('harness');
    expect(result.strategy).toBe('B:registry');
  });

  it('attempts trace records both miss + hit when A misses and B hits', () => {
    writeRegistry(scratch.home, {
      version: 2,
      plugins: {'harness@mp': [{installPath: scratch.pluginDir}]},
    });
    envHandle = withEnv(scratch.home, '/usr/bin');
    const result = resolvePluginRoot('harness');
    expect(result.attempts).toHaveLength(2);
    expect(result.attempts[0]).toBe('A path-bin: miss');
    expect(result.attempts[1]).toBe('B registry: hit');
  });

  it('PluginRootError message format matches Python verbatim', () => {
    envHandle = withEnv(scratch.home, '/usr/bin');
    try {
      resolvePluginRoot('harness');
      expect.fail('expected resolve to throw');
    } catch (err) {
      const expected =
        "플러그인 'harness' 루트 해석 실패 — " +
        'attempts: A path-bin: miss, B registry: miss, C mp-source: miss';
      expect((err as Error).message).toBe(expected);
    }
  });
});
